name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Push to SFTP
        uses: AbleLincoln/push-to-sftp@v1.2
        with:
          host: ${{ secrets.host }}
          port: 22
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          sourceDir: .
          targetDir: ./html/

